repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.9
        exclude: tests/.*/snapshots

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ['--select=F402,F404,F812,F823,F831,F821,F822,E112,E113,E901,E902,E999', '--ignore=G001,G002,G003']

  - repo: https://github.com/returntocorp/semgrep
    rev: v0.39.1
    hooks:
      - id: semgrep
        types: [python]
        args: ['-f', 'semgrep.yml', '--error']

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [ push ]
